server:
  port: 8080

spring:
  application:
    name: gateway
  output:
    ansi:
      enabled: always   # принудительно включить цвета (по умолчанию auto)cloud:
    gateway:
      routes:
        - id: backend
          uri: lb://backend          # lb:// = через Eureka + балансировка
          predicates:
            - Path=/api/**           # всё что /api/* → идёт на backend
        - id: frontend
          uri: lb://frontend
          predicates:
            - Path=/**               # всё остальное → на frontend

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info