server:
  port: 8080

spring:
  application:
    name: gateway
  output:
    ansi:
      enabled: always   # принудительно включить цвета (по умолчанию auto)
  cloud:
    gateway:
      mvc:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info