server.port=8761
spring.application.name=eureka-server
# принудительно включить цвета (по умолчанию auto)
spring.output.ansi.enabled=always
#  сам себя не регистрирует
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# # быстрый старт
eureka.server.wait-time-in-ms-when-sync-empty=0